# Generated by Django 4.2.5 on 2024-07-25 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincontent',
            name='pub_date',
        ),
    ]
