# Generated by Django 4.2.5 on 2024-07-26 06:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_remove_maincontent_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontent',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
